# permissions for end users to edit mydbdbaasinventories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mydbdbaasinventory-editor-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - mydbdbaasinventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - mydbdbaasinventories/status
  verbs:
  - get
