# permissions for end users to view mydbdbaasconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mydbdbaasconnection-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - mydbdbaasconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - mydbdbaasconnections/status
  verbs:
  - get
