# permissions for end users to view mydbdbaasinventories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mydbdbaasinventory-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - mydbdbaasinventories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - mydbdbaasinventories/status
  verbs:
  - get
